### ISSUE TITLE
Error: Cannot find module 'setprototypeof'

### ISSUE THREAD

**Issue by kristofve** [hediet/vscode-drawio#13]
I'm trying to load this extension into VS Code on Windows, but I cannot get it to load correctly. Some module seems to be missing.

Here is the relevant log information:

```javascript
[2020-05-11 14:39:37.165] [exthost] [error] Activating extension hediet.vscode-drawio failed due to an error:
[2020-05-11 14:39:37.166] [exthost] [error] Error: Cannot find module 'setprototypeof'
Require stack:
- c:\Users\<user>\.vscode\extensions\hediet.vscode-drawio-0.2.0\node_modules\http-errors\index.js
- c:\Users\<user>\.vscode\extensions\hediet.vscode-drawio-0.2.0\node_modules\send\index.js
- c:\Users\<user>\.vscode\extensions\hediet.vscode-drawio-0.2.0\node_modules\serve-static\index.js
- c:\Users\<user>\.vscode\extensions\hediet.vscode-drawio-0.2.0\out\DrawioAppServer\SelfHostedDrawioAppServer.js
- c:\Users\<user>\.vscode\extensions\hediet.vscode-drawio-0.2.0\out\DrawioAppServer\index.js
- c:\Users\<user>\.vscode\extensions\hediet.vscode-drawio-0.2.0\out\extension.js
- c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Module._load (internal/modules/cjs/loader.js:622:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\<user>\.vscode\extensions\hediet.vscode-drawio-0.2.0\node_modules\http-errors\index.js:16:22)
	at Module.o._compile (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\<user>\.vscode\extensions\hediet.vscode-drawio-0.2.0\node_modules\send\index.js:15:19)
	at Module.o._compile (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\<user>\.vscode\extensions\hediet.vscode-drawio-0.2.0\node_modules\serve-static\index.js:20:12)
	at Module.o._compile (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\<user>\.vscode\extensions\hediet.vscode-drawio-0.2.0\out\DrawioAppServer\SelfHostedDrawioAppServer.js:15:21)
	at Module.o._compile (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\<user>\.vscode\extensions\hediet.vscode-drawio-0.2.0\out\DrawioAppServer\index.js:7:10)
	at Module.o._compile (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\<user>\.vscode\extensions\hediet.vscode-drawio-0.2.0\out\extension.js:8:27)
	at Module.o._compile (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:33:115)
	at h._loadCommonJSModule (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:926:266)
	at h._doActivateExtension (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:822:856)
	at h._activateExtension (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:821:937)
	at Object.actualActivateExtension (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:883)
	at e._activateExtension (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:859)
	at c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:537
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:525)
	at e.activateByEvent (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:596:14)
	at h._activateByEvent (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:820:618)
	at c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:829:401
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by hediet** [comment]
That's a funny error. Which version of VS Code do you use? Until fixed, you should be fine by disabling the offline mode.

**Comment by kristofve** [comment]
I'm currently using 1.45.0, with Node.js version 12.8.1. Unfortunately, using the offline mode doesn't seem to fix it.

**Comment by hediet** [comment]
I have no idea why it wouldn't work.

![image](https://user-images.githubusercontent.com/2931520/81639708-fe9e3e00-941c-11ea-979a-ad8433955bfa.png)

Can you try to debug it? The `setprototypeof` is definitely shipped with the extension. Maybe a re-install helps?

**Comment by kristofve** [comment]
Reinstalling is something I've tried a few times already. I'm not really familiar with the way the node packaging system works, so my abilities to debug this are rather limited. Here is the listing of node modules that get installed along with the extension, is `setprototypeof` supposed to be in here?

```
    Directory: C:\Users\<user>\.vscode\extensions\hediet.vscode-drawio-0.2.0\node_modules


Mode                LastWriteTime         Length Name                                                                                                                                                             
----                -------------         ------ ----                                                                                                                                                             
d-----        5/11/2020  12:30 PM                @hediet                                                                                                                                                          
d-----        5/11/2020  12:30 PM                @sinonjs                                                                                                                                                         
d-----        5/11/2020  12:30 PM                @types                                                                                                                                                           
d-----        5/11/2020  12:30 PM                array-from                                                                                                                                                       
d-----        5/11/2020  12:30 PM                assertion-error                                                                                                                                                  
d-----        5/11/2020  12:30 PM                chai                                                                                                                                                             
d-----        5/11/2020  12:30 PM                check-error                                                                                                                                                      
d-----        5/11/2020  12:30 PM                debug                                                                                                                                                            
d-----        5/11/2020  12:30 PM                deep-eql                                                                                                                                                         
d-----        5/11/2020  12:30 PM                depd                                                                                                                                                             
d-----        5/11/2020  12:30 PM                destroy                                                                                                                                                          
d-----        5/11/2020  12:30 PM                diff                                                                                                                                                             
d-----        5/11/2020  12:30 PM                ee-first                                                                                                                                                         
d-----        5/11/2020  12:30 PM                encodeurl                                                                                                                                                        
d-----        5/11/2020  12:30 PM                escape-html                                                                                                                                                      
d-----        5/11/2020  12:30 PM                etag                                                                                                                                                             
d-----        5/11/2020  12:30 PM                finalhandler                                                                                                                                                     
d-----        5/11/2020  12:30 PM                fresh                                                                                                                                                            
d-----        5/11/2020  12:30 PM                get-func-name                                                                                                                                                    
d-----        5/11/2020  12:30 PM                has-flag                                                                                                                                                         
d-----        5/11/2020  12:30 PM                http-errors                                                                                                                                                      
d-----        5/11/2020  12:30 PM                inherits                                                                                                                                                         
d-----        5/11/2020  12:30 PM                just-extend                                                                                                                                                      
d-----        5/11/2020  12:30 PM                lodash                                                                                                                                                           
d-----        5/11/2020  12:30 PM                lolex                                                                                                                                                            
d-----        5/11/2020  12:30 PM                mime                                                                                                                                                             
d-----        5/11/2020  12:30 PM                mobx                                                                                                                                                             
d-----        5/11/2020  12:30 PM                ms                                                                                                                                                               
d-----        5/11/2020  12:30 PM                nise                                                                                                                                                             
d-----        5/11/2020  12:30 PM                on-finished                                                                                                                                                      
d-----        5/11/2020  12:30 PM                parseurl                                                                                                                                                         
d-----        5/11/2020  12:30 PM                pathval                                                                                                                                                          
d-----        5/11/2020  12:30 PM                range-parser                                                                                                                                                     
d-----        5/11/2020  12:30 PM                send                                                                                                                                                             
d-----        5/11/2020  12:30 PM                serve-static                                                                                                                                                     
d-----        5/11/2020  12:30 PM                sinon                                                                                                                                                            
d-----        5/11/2020  12:30 PM                statuses                                                                                                                                                         
d-----        5/11/2020  12:30 PM                supports-color                                                                                                                                                   
d-----        5/11/2020  12:30 PM                type-detect                                                                                                                                                      
d-----        5/11/2020  12:30 PM                unpipe                                                                                                                                                           
d-----        5/11/2020  12:30 PM                xml-formatter                                                                                                                                                    
d-----        5/11/2020  12:30 PM                xml-parser-xo
```

**Comment by hediet** [comment]
Yes, it is supposed to be in there :D Also, there is new version (v0.3.0), but it should not fix your problem.
The thing that I upload and vscode downloads from the store is a so called vsix package.
This .vsix-file is nothing else but a zip archive. You can download it from [here](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio) with the "Download Extension" button.

Can you install the new version the usual way and compare your file listing you sent me to the content of this vsix file? Maybe a virus scanner prevented the successful extraction of the file?

**Comment by kristofve** [comment]
I don't know if it was the new version or installing from .vsix, but either way it's working now! The node package is present in the directory.

> Maybe a virus scanner prevented the successful extraction of the file?

I suppose I might have been connected to my company's VPN which prevented downloading some libraries from npm. I've had trouble with using that VPN and maven in the past, so I wouldn't put it past it. Thanks for your work!

**Comment by hediet** [comment]
That nice to hear!

**Comment by hediet** [comment]
@kristofve for the sake of https://github.com/microsoft/vscode/issues/98159, can you try to reproduce this bug, so that @sandy081 can try to fix it?
