### ISSUE TITLE
Plugin not working when starting VS Code (insiders) from Windows 10 WSL2

### ISSUE THREAD

**Issue by mastoj** [hediet/vscode-drawio#159]
I just installed the plugin in my WSL2 instance of VS Code and can't it to work. When opening a ".drawio" file nothing happens basically.

Anything I can do to help debug? It works fine when I open it from Windows 10.

**Comment by hediet** [comment]
Thanks for your report!

Can you open the dev tools and/or the webview dev tools and see whether any Draw.io specific errors are logged?

Does the webview show? Can you see the loading screen?

**Comment by mastoj** [comment]
That was some quick response. 

I saw something that said I should try to open the file again, but when I do so all I get is blank and I can't do anything in the blank view.

I don't see any error in dev tools either. Is there some kind of debug flag I can use to get more info?

**Comment by mastoj** [comment]
I got an exception now:

```
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Update Webview Html]' Error: Webview is disposed
	at b.assertNotDisposed (/home/tomas/.vscode-server-insiders/bin/66b696427273f5d4711cf37a48b57594074f4ee3/out/vs/server/remoteExtensionHostProcess.js:865:836)
	at b.set html [as html] (/home/tomas/.vscode-server-insiders/bin/66b696427273f5d4711cf37a48b57594074f4ee3/out/vs/server/remoteExtensionHostProcess.js:865:225)
	at u.autorun.name (/home/tomas/.vscode-server-insiders/extensions/hediet.vscode-drawio-1.0.2/dist/extension/index.js:429:200236)
	at a (/home/tomas/.vscode-server-insiders/extensions/hediet.vscode-drawio-1.0.2/dist/extension/index.js:16:26371)
	at ce (/home/tomas/.vscode-server-insiders/extensions/hediet.vscode-drawio-1.0.2/dist/extension/index.js:16:9596)
	at e.track (/home/tomas/.vscode-server-insiders/extensions/hediet.vscode-drawio-1.0.2/dist/extension/index.js:16:22525)
	at e.onInvalidate (/home/tomas/.vscode-server-insiders/extensions/hediet.vscode-drawio-1.0.2/dist/extension/index.js:16:26179)
	at e.runReaction (/home/tomas/.vscode-server-insiders/extensions/hediet.vscode-drawio-1.0.2/dist/extension/index.js:16:22233)
	at et (/home/tomas/.vscode-server-insiders/extensions/hediet.vscode-drawio-1.0.2/dist/extension/index.js:16:24130)
	at Je (/home/tomas/.vscode-server-insiders/extensions/hediet.vscode-drawio-1.0.2/dist/extension/index.js:16:23766)
	at Ze (/home/tomas/.vscode-server-insiders/extensions/hediet.vscode-drawio-1.0.2/dist/extension/index.js:16:23822)
	at Ke (/home/tomas/.vscode-server-insiders/extensions/hediet.vscode-drawio-1.0.2/dist/extension/index.js:16:19905)
	at xe (/home/tomas/.vscode-server-insiders/extensions/hediet.vscode-drawio-1.0.2/dist/extension/index.js:16:11945)
	at Se (/home/tomas/.vscode-server-insiders/extensions/hediet.vscode-drawio-1.0.2/dist/extension/index.js:16:11365)
	at Module.dt (/home/tomas/.vscode-server-insiders/extensions/hediet.vscode-drawio-1.0.2/dist/extension/index.js:16:25774)
	at /home/tomas/.vscode-server-insiders/extensions/hediet.vscode-drawio-1.0.2/dist/extension/index.js:429:198329
	at l.fire (/home/tomas/.vscode-server-insiders/bin/66b696427273f5d4711cf37a48b57594074f4ee3/out/vs/server/remoteExtensionHostProcess.js:45:801)
	at w.$acceptConfigurationChanged (/home/tomas/.vscode-server-insiders/bin/66b696427273f5d4711cf37a48b57594074f4ee3/out/vs/server/remoteExtensionHostProcess.js:921:628)
	at /home/tomas/.vscode-server-insiders/bin/66b696427273f5d4711cf37a48b57594074f4ee3/out/vs/server/remoteExtensionHostProcess.js:920:889
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by hediet** [comment]
Oh, maybe that error is independant from your problem.

I need to try to reproduce your issue.

In the meantime, you can try to set the "offline" setting to false. Maybe that helps.

**Comment by mastoj** [comment]
@hediet, setting offline to false worked fine. Can I do something else to help debug the issue?

**Comment by hediet** [comment]
@mastoj You could post a screenshot or a video that shows the bug so I get a better understanding of the context.
Also, you could open the webview developer tools (`Developer: Open webview developer tools`). Maybe it lists some errors.
Thanks for your help!

When the offline mode works again, you should switch back to it. It is better integrated into VS Code!

**Comment by mastoj** [comment]
I wish I could, but now when I switched back to offline mode it is still working 😆 ... so I can't reproduce it I'm afraid. I'll update the issue if it happens again.

**Comment by hediet** [comment]
I see, a heisenbug it is ;)

**Comment by hediet** [comment]
Please reopen this issue if there is something I can do ;)
