### ISSUE TITLE
extensions don't work in WSL

### ISSUE THREAD

**Issue by L0laapk3** [hediet/vscode-drawio#407]
I have tried:
* https://marketplace.visualstudio.com/items?itemName=nopeslide.vscode-drawio-plugin-wavedrom
* https://marketplace.visualstudio.com/items?itemName=dzylikecode.vscode-drawio-plugin-markdown

Both worked in a windows native environment, but neither worked in a WSL environment (using the official WSL plugin: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)

The current behavior is that drawio looks and acts as if there are no extensions installed.

**Comment by darsor** [comment]
I am experiencing the same thing in a Remote (ssh) environment. The plugins work fine on the native windows host, but don't work on remote Linux hosts.

**Comment by bjorn-einar-bjartnes-4ss** [comment]
Get the same, the error i get is
<img width="416" alt="image" src="https://github.com/hediet/vscode-drawio/assets/88324093/d3dfdf59-d3db-4389-a77f-d9fc88acc44f">

**Comment by darsor** [comment]
I think this issue is unrelated to what you're seeing. We get no error message, it simply behaves like the plugins are not installed. Adding vscode-app to UNCHosts had no effect.

**Comment by jgroom33** [comment]
This behavior is also exhibited with `hediet.vscode-drawio.customLibraries`

### Environment:
Windows 11 + WSL Ubuntu 24.04

Config:
```json
    "hediet.vscode-drawio.customLibraries": [
        {
            "file": "${workspaceFolder}/drawio/Scratchpad.xml",
            "libName": "test",
            "entryId": "test"
        }
    ],
```

### Behavior (Extension Host Logs)
Notice the `C:\home\jgroom\src\lab\drawio\Scratchpad.xml`

This should be the WSL path /home/jgrom/src/lab/drawio/Scratchpad.xml

```
2025-05-01 13:04:25.722 [error] EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'C:\home\jgroom\src\lab\drawio\Scratchpad.xml'
	at Yi.e (file:///c:/Users/jgroom/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:18041)
	at Object.readFile (file:///c:/Users/jgroom/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:16562)
```

### Workaround:

Preferences on the remote:

```json
{ 
  "security.allowedUNCHosts": ["wsl$"]
}
```

```json
    "hediet.vscode-drawio.customLibraries": [
        {
            "file": "\\\\wsl$\\Ubuntu-24.04\\home\\jgroom\\src\\lab\\drawio\\Scratchpad.xml",
            "libName": "test",
            "entryId": "test"
        }
    ],
```

Possibly caused by #467
