### ISSUE TITLE
Stuck Loading on v0.4

### ISSUE THREAD

**Issue by jacokok** [hediet/vscode-drawio#43]
Not able to open file becuase it is stuck loading since version 0.4.
When I downgrade to 0.3 it works fine.

Vscode version: 1.45.1 on windows.

**Comment by hediet** [comment]
Can you try to open the webview dev tools and send me a screenshot of the logs?

**Comment by hediet** [comment]
v0.4.0 with VS Code 1.45.1 works fine for me on windows 10:

![image](https://user-images.githubusercontent.com/2931520/82306605-8eb12a00-99bf-11ea-9ab3-fd9e6351b688.png)

**Comment by jacokok** [comment]
![image](https://user-images.githubusercontent.com/5338052/82312478-675e5b00-99c7-11ea-9209-afa4a9f81800.png)

- c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Module._load (internal/modules/cjs/loader.js:622:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\f4805615\.vscode\extensions\hediet.vscode-drawio-0.4.0\node_modules\http-errors\index.js:16:22)
	at Module.o._compile (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\f4805615\.vscode\extensions\hediet.vscode-drawio-0.4.0\node_modules\send\index.js:15:19)
	at Module.o._compile (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\f4805615\.vscode\extensions\hediet.vscode-drawio-0.4.0\node_modules\serve-static\index.js:20:12)
	at Module.o._compile (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\f4805615\.vscode\extensions\hediet.vscode-drawio-0.4.0\out\DrawioAppServer\SelfHostedDrawioAppServer.js:15:21)
	at Module.o._compile (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\f4805615\.vscode\extensions\hediet.vscode-drawio-0.4.0\out\DrawioAppServer\index.js:7:10)
	at Module.o._compile (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (c:\Users\f4805615\.vscode\extensions\hediet.vscode-drawio-0.4.0\out\extension.js:8:27)
	at Module.o._compile (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:955:769)
	at Function.n._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:925:106)
	at Function.i._load (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:33:115)
	at h._loadCommonJSModule (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:926:266)
	at h._doActivateExtension (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:822:856)
	at h._activateExtension (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:821:937)
	at Object.actualActivateExtension (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:883)
	at e._activateExtension (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:859)
	at c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:537
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:525)
	at e.activateByEvent (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:596:14)
	at h._activateByEvent (c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:820:618)
	at c:\Users\f4805615\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:829:401
	at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by hediet** [comment]
Ah this error again. Can you try to uninstall the extension and install it again?

**Comment by jacokok** [comment]
![image](https://user-images.githubusercontent.com/5338052/82313110-33376a00-99c8-11ea-8d6e-86fffccee01a.png)

Thanks for help. 
It could be my company network causing this but I thought it was all packed to be available offline.

**Comment by hediet** [comment]
Yes. It is all packed to be available offline...

**Comment by jacokok** [comment]
Reinstalling did not resolve this for me.
However rolling back to v0.3 fixes it.

**Comment by hediet** [comment]
[Can you install the extension manually?](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio)
Just click on download there.

**Comment by jacokok** [comment]
This fixed the problem thank you.

**Comment by hediet** [comment]
@jacokok for the sake of https://github.com/microsoft/vscode/issues/98159, can you try to reproduce this bug, so that @sandy081 can try to fix it? Thank you very much ;)
